name: Homebrew
on:
  release:
    types:
      - published
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: tailcallhq/homebrew-tailcall
          ref: main
          token: ${{ secrets.HOMEBREW_ACCESS }}

      - name: Update homebrew formula
        run: ./update-formula.sh ${{ github.event.release.tag_name }}

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "update tailcall cli version: ${{ github.event.release.tag_name }}"
          git push
